%This script demonstrates how to produce an .xyz coordinate file for
%naphthalene by using its molecular symmetry. 

%The molecule lies in the xy plane.

%All C-C bonds are assumed to be 1.40 Angstroms.
%All C-H bonds are assumed to be 1.09 Angstroms.

natoms=18;        %Number of atoms in naphthalene = 18.
atoms=cell(18,1); %Initialisation of the atom label array for the 18 atoms.  
xyz=zeros(18,3);  %Initialisation of the x,y,z coordinate array for the 18 atoms.
atoms{1}='C';     %Label for atom C1.
atoms{2}='H';     %Label for atom H2
xyz(1,2)=1.4;     %The origin of the coordinate system is taken as the centre of the right hand ring. 
                  %So the coordinate of the C1 atom is (0,1.4,0)
              
xyz(2,2)=2.49; %The coordinate of the H2 atom is therefore (0,2.49,0) as 1.40 + 1.09 = 2.49 Angstroms

theta=-60;     %Six membered ring with internal C-C-C angles of 60 degrees. 

%Contruction of a C6 rotation matrix for rotation along the z-axis.
ct=cosd(theta);
st=sind(theta);
C6=eye(3);
C6(1,1)=ct;
C6(1,2)=-st;
C6(2,1)=st;
C6(2,2)=ct;

%Using the xyz coordinates for the C1 atom, the coordinates for C3, C5, C7,
%and C9 are generated by applying the rotation matrix to each C atom
%sequentially. E.g xyz of C3 = C6rotation * xyz of C1. 
%                  xyz of C5 = C6rotation * xyz of C3. 
for i=3:2:9
    iold=i-2;
    xyz(i,:)=C6*xyz(iold,:)';
    atoms{i}='C';              % The C atom labels are also sequentially added to the atom label array. 
end 

%The C10 xyz coordinate by applying the rotation matrix to the C9 xyz
xyz(10,:)=C6*xyz(9,:)';
atoms{10}='C';

%Generation of the H4, H6, and H8 coordinates from the coordinate of the H2
%atom. This follows the same method as the above C atom coordinate
%generation. 
for i=4:2:8
    iold=i-2;
    xyz(i,:)=C6*xyz(iold,:)';
    atoms{i}='H';
end 
%The xyz coordainates for the C and H atoms in the right hand ring have now
%been constructed. Next is the construstion of the coordinates for the left hand ring.  

%Translation of the coordinate system origin to the centre of the C9-C10
%bond. 
cx=(xyz(9,1)+xyz(10,1))/2;
cy=(xyz(9,2)+xyz(10,2))/2;
cz=(xyz(9,3)+xyz(10,3))/2;

%Subtraction of these x,y,z values from the coordinates of all atoms mapped
%so far. 
for i=1:10
    xyz(i,1)=xyz(i,1)-cx;
    xyz(i,2)=xyz(i,2)-cy;
    xyz(i,3)=xyz(i,3)-cz;
end 

%Initialisation of a reflection matrix, for reflection in the yz plane. 
sigmayz=eye(3);
sigmayz(1,1)=-1;

%Generation of the C17, C15, C13, and C11 atom coordinates. 
%C17 is generated by applying the reflection matrix to C1.
%C15 is generated by applying the reflection matrix to C3.
%C13 is generated by applying the reflection matrix to C5.
%C11 is generated by applying the reflection matrix to C7.
inew=19
for i=1:2:7
    inew=inew-2;
    xyz(inew,:)=xyz(i,:)*sigmayz;
    atoms{inew}='C';
end 

%The same process as above but for the generation of atoms H18, H16, H14,
%and H12. 
inew=20
for i=2:2:8
    inew=inew-2;
    xyz(inew,:)=xyz(i,:)*syz;
    atoms{inew}='H';
end 

%The xyz coordinates for all atoms in naphthalene have now been generated
%and stored in the 'xyz' array. The corresponding atom labels for each of the
%xyz coordinates are stored in the 'atoms' array. The coordinate will now
%be written to a .xyz coordinate file, ready to be used in a Molecular
%Dynamics simulation. 

fid=fopen('naphth.xyz','w');    %Create an .xyz file named 'naphth.xyz' ready for writing ('w').
fprintf(fid,'%d \n \n',natoms); %On the first line of the file print the number of atoms (natoms) as an integer 
                                %(%d), followed by a blank line (\n).

%Print the atom label followed by the x,y,z coordinates for all 18 atoms into the .xyz file.                                 
for i=1:natoms
    fprintf(fid,'%s %f %f %f \n',atoms{i},xyz(i,1),xyz(i,2),xyz(i,3)); %Print the atom label as a string(%s), followed 
end                                                                    %by the x,y,and z coordinates as floating point
                                                                       %values(%f).
%Finalise the construction of the .xyz file.
fclose(fid);
                                                                       
                                                                      
                                                                     
                                                                      
                                                                       
                                                                  
                                                                    



    
   

    
        
     
    
    


    







